package tgb.btc.web.constant.enums;

public enum NotificationType {
    NEW_BOT_DEAL,
    ADDITIONAL_VERIFICATION_RECEIVE,
    NEW_API_DEAL,
    API_DEAL_CANCELED,
    ADD_MANUAL_DEAL,
    CONFIRM_BOT_DEAL,
    DELETE_BOT_DEAL,
    ADDITIONAL_VERIFICATION_REQUEST

}
